global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # -----------------------------
  # Scrape Prometheus Pushgateway metrics
  # -----------------------------
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  # -----------------------------
  # Scrape Prefect Server metrics
  # -----------------------------
  - job_name: 'prefect'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['prefect-server:4200']

  # -----------------------------
  # Optional: scrape Prometheus itself
  # -----------------------------
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
